# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl: /tufte-css-jekyll
title: tufte-css-jekyll
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: A Jekyll theme based on tufte-css
author: Stephan Druskat
email: mail [at] sdruskat [dot]
description: A Jekyll theme based on tufte-css
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: Europe/Berlin
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: src